[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["testing"]
include = ["pyares_Ax*"]

[project]
name = "pyares-Ax"
version = "0.4.0"
requires-python = ">= 3.11"
authors = [{ name = "AFRL", email = "AFRL.RX.AREScontact@us.af.mil" }]
description = "PyAres Compatible Baysian Optimizaiton Planners based on Meta's Ax API"
license = "MIT"
dependencies = [
    "PyAres (>=1.0.0b1)",
    "ax-platform (>=1.2.0)",
    "pandas (>=3.0.0)",
    "matplotlib (>=3.10.0)",
    "sympy (>=1.14.0)",
    "openpyxl (>=3.0.0)",
]
readme = "readme.md"

[project.urls]
"Homepage" = "https://github.com/AFRL-ARES"

