from testing.synthetic_process_space import SyntheticProcessResponse
import numpy as np
from ax.service.ax_client import AxClient, ObjectiveProperties

import pandas as pd
import matplotlib.pyplot as plt


# Generated by Honegumi (https://arxiv.org/abs/2502.06815)

params = {'temperature':[165.0,280.0],
          'extrusion_rate':[0.5,1.5]
          }
obj1_name = 'Dissimilarity'
resonse_surface = SyntheticProcessResponse(param_bounds=params,output_bounds=(1,10000))


ax_client = AxClient()

parameters = [{'name':k,'type':'range','bounds':params[k]} for k in params.keys()]
# Define your search space and objectives
ax_client.create_experiment(parameters=parameters,
                            objectives={obj1_name: ObjectiveProperties(minimize=True)}
                            )


# optimization loop
for i in range(30):

    # get_next_trial performs model fitting and acquisition function evaluation
    parameterization, trial_index = ax_client.get_next_trial()

    # extract parameters
    temperature = parameterization["temperature"]
    extrusion_rate = parameterization["extrusion_rate"]

    # evaluate the dummy objective function
    results = resonse_surface.evaluate(parameterization)
    # report the results back to the algorithm
    ax_client.complete_trial(trial_index=trial_index, raw_data=results)

# best in-sample parameterization as predicted by model
best_parameters, metrics = ax_client.get_best_parameters()


# Plot results
objectives = ax_client.objective_names
df = ax_client.get_trials_data_frame()

fig, ax = plt.subplots(figsize=(6, 4), dpi=150)
ax.scatter(df.index, df[objectives], ec="k", fc="none", label="Observed")
ax.plot(
    df.index,
    np.minimum.accumulate(df[objectives]),
    color="#0033FF",
    lw=2,
    label="Best to Trial",
)
ax.set_xlabel("Trial Number")
ax.set_ylabel(objectives[0])

ax.legend()
plt.show()
# if len(params.keys())==2:

# def plot_surface_2d_3d(response_surface, planning_parameters, results,res=100):
#     p_dict = {}
#     bounds = []
#     param_names = []
#     for p in params:
#         name = p.name
#         param_names.append(name)
#         bounds.append((p.minimum_value,p.maximum_value))
#         values = []
#         for iteration in p.param_history[1:]: # Drop the first entry as a it is empty
#             values.append(iteration.planned_value)
#         p_dict[name]=np.array(values)

#     #Generate Grid for Plotting
#     x = np.linspace(bounds[0][0], bounds[0][1], res)
#     y = np.linspace(bounds[1][0], bounds[1][1], res)
#     X, Y = np.meshgrid(x, y)
#     Z = np.zeros_like(X)

#     for i in range(X.shape[0]):
#         for j in range(X.shape[1]):
#             Z[i, j] = response_surface.evaluate({param_names[0]: X[i, j], param_names[1]: Y[i, j]})
#     fig, ax = plt.subplots()
#     contour = ax.contourf(X, Y, Z, levels=30, cmap='viridis', alpha=0.8)
#     fig.colorbar(contour, ax=ax, label='Objective Value')
    
#     # Plot path on 2D
#     ax.scatter(p_dict[param_names[0]], p_dict[param_names[1]], c='white', edgecolor='black', s=30, alpha=0.6, label='Samples')

#     ax.scatter(p_dict[param_names[0]][np.argmin(results)], p_dict[param_names[1]][np.argmin(results)], c='red', marker='*', s=200, label='Best Found', zorder=10)
#     # Connect the dots to show sequence
    
#     ax.set_title("2D Landscape")
#     ax.set_xlabel(f"Param: {param_names[0]}")
#     ax.set_ylabel(f"Param: {param_names[1]}")
#     ax.legend()
#     plt.show()